#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "lauti"
name = "Lauti"
description.en = "Open Source Community Calendar. Invite friends, groups and places and let them fill the site with their events. Use it for independent calenders for cities or regions, for political and cultural events, demonstrations, activism, special interest communities and everything you can imagine."
description.fr = "Open Source Community Calendar. Invite friends, groups and places and let them fill the site with their events. Use it for independent calenders for cities or regions, for political and cultural events, demonstrations, activism, special interest communities and everything you can imagine."

version = "1.2~ynh1"

maintainers = ["matebitte"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "AGPL-3.0-only"
website = "https://lauti.org/"
demo = "https://eintopf.info/"
admindoc = "https://lauti.org/docs/admin/theming/"
userdoc = "https://lauti.org/docs/user/backstage/"
code = "https://codeberg.org/Klasse-Methode/lauti"

# FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is
# sort of a standard id for applications defined by the NIST. In particular, YunoHost may use this is in the future
# to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here:
# https://nvd.nist.gov/products/cpe/search.
# For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
# cpe = "???"

# FIXME: optional but recommended (or remove if irrelevant / not applicable).
# This is meant to be an URL where people can financially support this app, especially when its development is based
# on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.
# fund = "???"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
# FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = "false"
sso = "false"

# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "200M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "path"
    default = "/"

    [install.init_main_permission]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # This won't be saved as setting and will instead be used to initialize the SSOwat permission
    type = "group"
    default = "visitors"

    # FIXME add more supported languages
    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choose the application language"
    type = "select"
    choices = ["en", "de"]
    default = "en"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # Note that user-provided passwords questions are not automatically saved as setting
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

    [resources.sources.main]
    architectures.amd64.url = "https://codeberg.org/Klasse-Methode/lauti/releases/download/v1.2.0/lauti-v1.2.0-linux-amd64"
    architectures.amd64.sha256 = "b523443b7fa100e9f8ded13e624fb585813627e180425cbcd5473c789547dbfa"
    architectures.arm64.url = "https://codeberg.org/Klasse-Methode/lauti/releases/download/v1.2.0/lauti-v1.2.0-linux-arm64"
    architectures.arm64.sha256 = "4dbbc996787b5be2527a2c91757db59ef96d332d4dc45ca1a540977c4ec2b91b"

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = "go"

    # [resources.database]
    # This will automatically provision/deprovison a MySQL DB and store the corresponding credentials in settings $db_user, $db_name, $db_pwd
    # type = "mysql"
